In [1]:
import os
import sys
sys.path.append("..")

In [23]:
from saxpy import paa

ModuleNotFoundError: No module named 'saxpy'

In [24]:
import numpy as np
def paa(series, paa_segments):
    """PAA implementation."""
    series_len = len(series)

    # check for the trivial case
    if (series_len == paa_segments):
        return np.copy(series)
    else:
        res = np.zeros(paa_segments)
        if (series_len % paa_segments == 0):
            inc = series_len // paa_segments
            for i in range(0, series_len):
                idx = i // inc
                res[idx] = res[idx] + series[i]
            return res / inc
        else:
            for i in range(0, paa_segments * series_len):
                idx = i // series_len
                pos = i // paa_segments
                res[idx] = res[idx] + series[pos]
            return res / series_len

In [11]:
ts = np.array([1, 1, 2, 2, 3, 3])

In [12]:
paa(ts, 6)

array([1, 1, 2, 2, 3, 3])

In [13]:
paa(ts, 3)

array([ 1.,  2.,  3.])

In [20]:
paa(paa(ts, 4), 6)

array([ 1.        ,  1.33333333,  1.66666667,  2.33333333,  2.66666667,  3.        ])

In [25]:
dat = np.array([-0.9796808, -0.8622706, -0.6123005, 0.8496459, 1.739691,
                    1.588194, 1.095829, 0.5277147, 0.4709033, -0.2865819,
                    0.0921607, -0.2865819, -0.9039323, -1.195564, -1.237226])

paa(dat, 10)

array([-0.94054407, -0.69562387,  1.1463276 ,  1.638693  ,  0.90645757,
        0.48984043, -0.16033437, -0.16033437, -1.00114287, -1.22333867])

In [26]:
dat_paa = np.array([-0.9405441, -0.6956239, 1.146328, 1.638693, 0.9064573,
                        0.4898404, -0.1603344, -0.1603344, -1.001143,
                        -1.223339])
dat_paa - paa(dat, 10)

array([ -3.33333332e-08,  -3.33333333e-08,   4.00000000e-07,
        -4.44089210e-16,  -2.66666667e-07,  -3.33333331e-08,
        -3.33333333e-08,  -3.33333333e-08,  -1.33333333e-07,
        -3.33333333e-07])

In [8]:
os.getcwd()

'/home/psenin/git/saxpy/jupyter'

In [2]:
sys.path

['',
 '/home/psenin/anaconda3/lib/python36.zip',
 '/home/psenin/anaconda3/lib/python3.6',
 '/home/psenin/anaconda3/lib/python3.6/lib-dynload',
 '/home/psenin/anaconda3/lib/python3.6/site-packages',
 '/home/psenin/anaconda3/lib/python3.6/site-packages/IPython/extensions',
 '/home/psenin/.ipython',
 '..']