In [1]:
import os
import sys
sys.path.append("..")

In [3]:
from saxpy import znorm
ts = [-1., -2., -1., 0., 2., 1., 1., 0.]
z_thrsh = 0.001
x_scaled = [x / 100.0 for x in ts]
znorm.znorm(x_scaled, z_thrsh)

array([-0.81649658, -1.63299316, -0.81649658,  0.        ,  1.63299316,
        0.81649658,  0.81649658,  0.        ])

In [15]:
import numpy as np
def paa(series, paa_segments):
    """PAA implementation."""
    series_len = len(series)

    # check for the trivial case
    if (series_len == paa_segments):
        return np.copy(series)
    else:
        res = np.zeros(paa_segments)
        if (series_len % paa_segments == 0):
            inc = series_len // paa_segments
            for i in range(0, series_len):
                idx = i // inc
                res[idx] = res[idx] + series[i]
            return res / inc
        else:
            for i in range(0, paa_segments * series_len):
                idx = i // series_len
                pos = i // paa_segments
                res[idx] = res[idx] + series[pos]
            return res / series_len

In [11]:
ts = np.array([1, 1, 2, 2, 3, 3])

In [12]:
paa(ts, 6)

array([1, 1, 2, 2, 3, 3])

In [13]:
paa(ts, 3)

array([ 1.,  2.,  3.])

In [20]:
paa(paa(ts, 4), 6)

array([ 1.        ,  1.33333333,  1.66666667,  2.33333333,  2.66666667,  3.        ])

In [8]:
os.getcwd()

'/home/psenin/git/saxpy/jupyter'

In [2]:
sys.path

['',
 '/home/psenin/anaconda3/lib/python36.zip',
 '/home/psenin/anaconda3/lib/python3.6',
 '/home/psenin/anaconda3/lib/python3.6/lib-dynload',
 '/home/psenin/anaconda3/lib/python3.6/site-packages',
 '/home/psenin/anaconda3/lib/python3.6/site-packages/IPython/extensions',
 '/home/psenin/.ipython',
 '..']